{{- if .Values.secretManager.enabled }}
{{- range $component, $secrets := dict "order-api" .Values.secretManager.apiSecrets "order-book" .Values.secretManager.bookSecrets "batch-worker" .Values.secretManager.batchSecrets }}
{{- if $secrets }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Release.Name }}-{{ $component }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- range $secret := $secrets }}
      - resourceName: {{ $secret.resourceName | quote }}
        path: {{ $secret.path | quote }}
      {{- end }}
{{- else }}
{{- fail (printf "Provide secretManager file references for %s when enabled" $component) }}
{{- end }}
{{- end }}
{{- end }}
